---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-reader
roleRef:
  apiGroup: ''
  kind: ClusterRole
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: pod-reader-1
    namespace: trick3
