###
#
# Silly Kubectl Trick #2 - Listing Images (and Other Output Formats)
#
# This Kubernetes resource definition file is meant to accompany the
# Silly Kubectl Tricks video and blog series, specifically Trick #2,
# which is all about listing images via custom-columns output formats.
#
# Blog:  https://www.starkandwayne.com/blog/silly-kubectl-trick-2-listing-images/
# Video: (forthcoming)
#
###
---
apiVersion: v1
kind: Namespace
metadata:
  name: web-dashboard

---
apiVersion: v1
kind: Service
metadata:
  namespace: web-dashboard
  name: redis-cache
  labels:
    skt: "2"
spec:
  type: ClusterIP
  selector:
    service: redis-cache
  ports:
    - name: redis
      port: 2379
      targetPort: redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: web-dashboard
  name: redis-cache
  labels:
    skt: "2"
spec:
  replicas: 2
  serviceName: redis-cache
  selector:
    matchLabels:
      app: redis-cache

  template:
    metadata:
      labels:
        app:     redis-cache
        service: redis-cache
        skt:     "2"

    spec:
      containers:
        - name: redis
          image: redis:5.0-alpine3.11

          ports:
            - name: redis
              containerPort: 2379

---
apiVersion: v1
kind: Service
metadata:
  namespace: web-dashboard
  name: db
  labels:
    skt: "2"
spec:
  type: ClusterIP
  selector:
    service: db
  ports:
    - name: db
      port: 3306
      targetPort: db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: web-dashboard
  name: db
  labels:
    skt: "2"
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app:     db
        service: db
        skt: "2"

    spec:
      containers:
        - name: db
          image: mariadb:10.1-bionic

          env:
            - name:  MYSQL_ROOT_PASSWORD
              value: "sekrit"

          ports:
            - name: db
              containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web-dashboard
  name: admin-ui
  labels:
    skt: "2"
spec:
  selector:
    matchLabels: 
      app: admin-ui
  template:
    metadata:
      labels:
        app: admin-ui
        skt: "2"

    spec:
      containers:
        - name: web
          image: nginx:latest
          imagePullPolicy: Always

---
apiVersion: v1
kind: Namespace
metadata:
  name: web-front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web-front
  name: app-server
  labels:
    skt: "2"

spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
        skt: "2"

    spec:
      containers:
        - name: www
          image: nginx:stable-alpine-perl
          imagePullPolicy: Always

        - name: sessions
          image: redis:5.0.7-buster
