###
#
# Silly Kubectl Trick #11 - Getting At Those Logs
#
# This Kubernetes resource definition file is meant to accompany the
# Silly Kubectl Tricks video and blog series, specifially Trick #11,
# which is all about exec vs. attach
#
# Blog:  (forthcoming)
# Video: (forthcoming)
#
###
---
apiVersion: v1
kind: Namespace
metadata:
  name: trick11
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: trick11
  name: opt
data:
  run: |
    #!/bin/bash
    trap 'exit 1;' INT TERM QUIT
    read JUNK
    echo "Hello, welcome to the Pod!"
    echo "What is your name?"
    read -p "> " NAME
    echo
    echo "Pleased to meet you, $NAME"
    echo
    while true; do
      sleep 3600
    done
---
apiVersion: v1
kind: Pod
metadata:
  name: attach-to-me
  namespace: trick11
  labels:
    skt: "11"
spec:
  volumes:
    - name: opt
      configMap:
        name: opt
        defaultMode: 0755

  containers:
    - name:  main
      image: huntprod/run
      stdin: yes
      volumeMounts:
        - name: opt
          mountPath: /opt
